CREATE DATABASE employeedb;

USE employeedb;

CREATE TABLE TBL_EMPLOYEE 
(
	ID INT NOT NULL AUTO_INCREMENT,
    EMPID VARCHAR(11) NOT NULL UNIQUE,
    EMPFIRSTNAME VARCHAR(20) NOT NULL,
    EMPLASTNAME VARCHAR(20) NOT NULL,
    EMPGENDER VARCHAR(1) NOT NULL,
    EMPDOB DATE NOT NULL,
    PRIMARY KEY (ID)
);

DESC TBL_EMPLOYEE;
SHOW TABLES;

INSERT INTO TBL_EMPLOYEE 
(EMPID,EMPFIRSTNAME,EMPLASTNAME,EMPGENDER,EMPDOB)
VALUES
('I10','Priyabrat','Padhy','M','1994-05-30');

SELECT * FROM TBL_EMPLOYEE;
